#pragma once

#include <mutex>
#include <optional>
#include <string>
#include <string_view>

#include "app/control/ports/wifi-manager.hpp"
#include "domain/network/models/wifi-direct-group.hpp"

namespace sst::adapters::control {

// Resolve the WiFi interface name. If [requested] is a concrete name (not empty
// and not "auto") it is returned as-is. Otherwise the interface is detected at
// runtime: first the wpa_supplicant control socket present in [ctrl_dir] (the
// interface the daemon actually manages — the most reliable signal), then a
// wireless interface under [sysfs_dir] (one exposing phy80211). Falls back to
// "wlan0" only if nothing is found. Interface names are NOT stable across boards
// (this Jetson is "wlP1p1s0", not "wlan0"), so hardcoding is wrong.
auto ResolveWifiInterface(const std::string& requested, const std::string& ctrl_dir,
                          const std::string& sysfs_dir = "/sys/class/net") -> std::string;

// wpa_supplicant ctrl_iface adapter. Talks to the running wpa_supplicant daemon
// over a UNIX datagram socket at <ctrl_dir>/<iface>, sending plain-text commands
// and reading back OK/FAIL replies and unsolicited events.
//
// The device runs as a REAL autonomous (non-persistent) WiFi-Direct P2P group
// owner (KTD4): `P2P_GROUP_ADD` forms a group whose SSID + passphrase are
// generated by wpa_supplicant. The adapter reads them back (from the
// P2P-GROUP-STARTED event) and reports them so the app joins what the camera
// created. The on-device static-IP / DHCP / policy-routing is a separate
// provisioning concern (DhcpServer + deploy steps).
class WpaWifiManager final : public sst::control::IWifiManager {
   public:
    // iface defaults to "auto" — resolved at connect time via ResolveWifiInterface.
    explicit WpaWifiManager(std::string iface = "auto",
                            std::string ctrl_dir = "/run/wpa_supplicant");
    ~WpaWifiManager() override;

    WpaWifiManager(const WpaWifiManager&) = delete;
    auto operator=(const WpaWifiManager&) -> WpaWifiManager& = delete;
    WpaWifiManager(WpaWifiManager&&) = delete;
    auto operator=(WpaWifiManager&&) -> WpaWifiManager& = delete;

    auto StartP2pGroupOwner() -> std::optional<sst::network::WifiDirectGroup> override;
    auto Stop() -> void override;
    [[nodiscard]] auto State() const -> sst::control::WifiState override;

   private:
    [[nodiscard]] auto OpenCtrlSocket() -> bool;
    auto CloseCtrlSocket() -> void;
    auto SendCommand(std::string_view cmd) -> std::optional<std::string>;
    // Read datagrams until one contains `marker` (up to a bounded number of
    // reads) — used to capture the async P2P-GROUP-STARTED event.
    auto ReadUntil(std::string_view marker) const -> std::optional<std::string>;

    std::string iface_;
    std::string ctrl_dir_;
    int sock_{-1};
    std::string local_path_;

    mutable std::mutex mtx_;
    sst::control::WifiState state_{};
    std::string group_interface_;
};

}  // namespace sst::adapters::control
