line-length = 100

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["F401"]

[format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20